# Generated by Django 4.2.3 on 2023-07-23 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_icu_bed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDepartment',
            fields=[
                ('doctor_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_id', models.AutoField(primary_key=True, serialize=False)),
                ('nurse_name', models.CharField(max_length=100)),
                ('nurse_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NurseDepartment',
            fields=[
                ('nurse_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.department')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_address', models.CharField(max_length=200)),
                ('discharged', models.BooleanField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.bed')),
            ],
        ),
        migrations.CreateModel(
            name='NurseDepartmentHospital',
            fields=[
                ('nurse_department_hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.hospital')),
                ('nurse_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.nursedepartment')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDepartmentHospital',
            fields=[
                ('doctor_department_hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.doctordepartment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.department'),
        ),
        migrations.AddField(
            model_name='bed',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.doctor'),
        ),
        migrations.AddField(
            model_name='bed',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_workflow.nurse'),
        ),
    ]
